### PR TITLE
CI: Enable P_LKRG_JUMP_LABEL_STEXT_DEBUG in mainline test

### PR DESCRIPTION
**Pull request by vt-alt**
As discussed in https://github.com/lkrg-org/lkrg/issues/137

>  It might be useful to always enable P_LKRG_JUMP_LABEL_STEXT_DEBUG on mainline build.

### How Has This Been Tested?
https://github.com/vt-alt/lkrg/runs/5013353445

### CODE REVIEW

**Comment by Adam-pi3** [comment]
It's unrelated to this PR, but it looks like there is problem with docker build for centos:8
```
Run yum install -y kernel-devel kernel gcc make elfutils-libelf-devel
CentOS Linux 8 - AppStream                      178  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
Error: Process completed with exit code 1.
```

**Comment by vt-alt** [comment]
> It's unrelated to this PR, but it looks like there is problem with docker build for centos:8

Seems accidental error and no reproducible. Maybe it was some temporary network issue.

**Comment by solardiz** [comment]
The CentOS 8 build keeps failing like that. It failed after this PR was merged, then failed two more times as I tried to re-run the job.

**Comment by vt-alt** [comment]
Ah, I mis-thought it's centos stream. Yes, plain centos 8 is failing and other projects are removing it, such as LTP https://lists.linux.it/pipermail/ltp/2022-February/027417.html
Perhaps, we should do the same.

**Pull request merged**
